#!/usr/bin/env python3
"""
Direct management of Grist access rights in the PostgreSQL "home" database.

Lists, grants/changes or removes a user's access to a document, a workspace
or an organisation by directly manipulating the `groups`, `group_users` and
`acl_rules` tables — i.e. the equivalent of the
PATCH /api/{orgs,workspaces,docs}/:id/access endpoints in ApiServer.ts.

Data model (see documentation/database.md):
  - Each resource has role groups ('owners', 'editors', 'viewers', plus
    'members' for orgs and the automatically managed 'guests'), linked to
    the resource through the `acl_rules` table.
  - Granting a role to a user = inserting them into `group_users` for the
    matching group (and removing them from the resource's other role groups,
    since a user holds only one direct role per resource).
  - After any change on a doc or workspace, Grist "repairs" the `guests`
    groups of the parent resources (see _repairWorkspaceGuests and
    _repairOrgGuests in app/gen-server/lib/homedb/HomeDBManager.ts) so that
    users invited on a child resource can navigate down to it. This script
    reproduces that logic.

Examples:
  # List the access rights of a document (full id or url_id)
  ./grist_access.py --dsn "$DSN" list --doc 4gPu3Fj1zSKQ

  # Add someone to the owners of a document
  ./grist_access.py --dsn "$DSN" set --doc 4gPu3Fj1zSKQ --email alice@example.com --role owners

  # Demote someone to plain viewer on a workspace
  ./grist_access.py --dsn "$DSN" set --workspace 12 --email alice@example.com --role viewers

  # Remove all direct access to an organisation (numeric id or domain)
  ./grist_access.py --dsn "$DSN" remove --org my-team --email bob@example.com

  # Simulate without writing anything
  ./grist_access.py --dsn "$DSN" --dry-run set --doc 4gPu3Fj1zSKQ --email alice@example.com --role owners

  # Log every executed SQL query (to stderr and/or to a file)
  ./grist_access.py --dsn "$DSN" -v --log-file grist_access.log list --org testorg

The connection uses --dsn when provided, otherwise the usual libpq
environment variables (PGHOST, PGDATABASE, PGUSER, PGPASSWORD, ...).
"""

import argparse
import logging
import sys
import time
from typing import Literal

import psycopg2
import psycopg2.extras

try:
    from pygments import highlight
    from pygments.lexers import SqlLexer
    from pygments.formatters import Terminal256Formatter
except Exception():
    highlight = None
    pass


logger = logging.getLogger("grist_access")

OWNERS = "owners"
EDITORS = "editors"
VIEWERS = "viewers"
MEMBERS = "members"
GUESTS = "guests"

# Roles that can be assigned directly. 'guests' is excluded: it is managed
# automatically (repaired by this script just like by Grist itself).
ASSIGNABLE_ROLES = (OWNERS, EDITORS, VIEWERS, MEMBERS)
ROLE_GROUP_NAMES = (OWNERS, EDITORS, VIEWERS, MEMBERS, GUESTS)

# Special users (see app/common/UserAPI.ts): never added to guests groups
# (filterEveryone logic in UsersManager.ts).
EVERYONE_EMAIL = "everyone@getgrist.com"
ANONYMOUS_USER_EMAIL = "anon@getgrist.com"

MAX_INHERITED_ROLE = Literal["owners", "editors", "viewers"] | None

class Fatal(Exception):
    pass


class SqlLoggingConnection(psycopg2.extras.MinTimeLoggingConnection):
    """Logs every executed query through psycopg2's built-in
    LoggingConnection/LoggingCursor mechanism (cursors from this connection
    automatically log the query actually sent to the server, with parameters
    interpolated — including the INSERTs generated by execute_values).
    Only the formatting is overridden."""

    def filter(self, msg, curs):
        if isinstance(msg, bytes):
            msg = msg.decode("utf-8", "replace")
        # curs.timestamp is set by MinTimeLoggingCursor before execution.
        elapsed_ms = (time.time() - curs.timestamp) * 1000
        return "SQL [%.1f ms, rowcount=%s] %s" % (elapsed_ms, curs.rowcount, self.format_msg(msg))

    def format_msg(self, msg):
        return msg

class SynHighlighSqlLoggingConnection(SqlLoggingConnection):
    style = "default"
    def format_msg(self, msg):
        if not highlight:
            super().format_msg(msg)
        return highlight(msg, lexer=SqlLexer(), formatter=Terminal256Formatter(style=self.style))


def setup_logging(verbose, log_file):
    logger.handlers.clear()
    logger.setLevel(logging.DEBUG)
    logger.propagate = False
    fmt = logging.Formatter("%(asctime)s %(levelname)s %(message)s")
    if verbose:
        handler = logging.StreamHandler(sys.stderr)
        handler.setFormatter(fmt)
        logger.addHandler(handler)
    if log_file:
        handler = logging.FileHandler(log_file, encoding="utf-8")
        handler.setFormatter(fmt)
        logger.addHandler(handler)
    if not logger.handlers:
        logger.addHandler(logging.NullHandler())


# ---------------------------------------------------------------------------
# Resource and user resolution
# ---------------------------------------------------------------------------

def find_user(cur, email):
    """Returns (user_id, display_email) for a given email address."""
    cur.execute(
        """SELECT u.id, l.display_email FROM users u
           JOIN logins l ON l.user_id = u.id
           WHERE l.email = %s""",
        (email.strip().lower(),))
    row = cur.fetchone()
    if not row:
        raise Fatal(f"No user with email {email!r}. "
                    "The user must have logged in at least once "
                    "(or have been invited) to exist in the database.")
    return row[0], row[1]

def extract_resource_identifier(args: argparse.Namespace):
    selectors = [s for s in (args.org, args.workspace, args.doc) if s is not None]
    if len(selectors) != 1:
        raise Fatal("Specify exactly one resource: --org, --workspace or --doc.")
    if args.org is not None:
        return { 'org': int(args.org) if args.org.isdigit else args.org }
    if args.workspace is not None:
        if not args.workspace.isdigit():
            raise Fatal("--workspace expects a numeric id.")
        return { 'workspace': int(args.workspace) }
    return { 'doc': args.doc }

def resolve_resource(cur, res_identifier):
    """Returns a dict describing the targeted resource:
    {kind: 'org'|'workspace'|'doc', id, label, org_id, workspace_id}."""
    org = res_identifier.get('org')
    workspace = res_identifier.get('workspace')
    doc = res_identifier.get('doc')

    if org is not None:
        if isinstance(org, int):
            cur.execute("SELECT id, name FROM orgs WHERE id = %s", (int(org),))
        else:
            cur.execute("SELECT id, name FROM orgs WHERE domain = %s", (org,))
        row = cur.fetchone()
        if not row:
            raise Fatal(f"Organisation not found: {org!r} (id or domain).")
        return {"kind": "org", "id": row[0], "label": f"org #{row[0]} (\"{row[1]}\")",
                "org_id": row[0], "workspace_id": None}

    if workspace is not None:
        cur.execute(
            """SELECT w.id, w.name, w.org_id, o.name FROM workspaces w
               JOIN orgs o ON o.id = w.org_id WHERE w.id = %s""",
            (int(workspace),))
        row = cur.fetchone()
        return {"kind": "workspace", "id": row[0],
                "label": f"workspace #{row[0]} (\"{row[1]}\") in org (\"{row[3]}\")",
                "org_id": row[2], "workspace_id": row[0]}

    # Document: full id or url_id.
    cur.execute(
        """SELECT d.id, d.name, d.workspace_id, w.org_id FROM docs d
           JOIN workspaces w ON w.id = d.workspace_id
           WHERE d.id = %s OR d.url_id = %s""",
        (doc, doc))
    rows = cur.fetchall()
    if not rows:
        raise Fatal(f"Document not found: {doc!r} (id or url_id).")
    if len(rows) > 1:
        ids = ", ".join(r[0] for r in rows)
        raise Fatal(f"Several documents match {doc!r}: {ids}. "
                    "Use the full id.")
    row = rows[0]
    return {"kind": "doc", "id": row[0], "label": f"doc {row[0]} (\"{row[1]}\")",
            "org_id": row[3], "workspace_id": row[2]}


def get_role_groups(cur, res):
    """Returns {role_name: group_id} for the resource's role groups."""
    column = {"org": "org_id", "workspace": "workspace_id", "doc": "doc_id"}[res["kind"]]
    cur.execute(
        f"""SELECT g.name, g.id FROM acl_rules a
            JOIN groups g ON g.id = a.group_id
            WHERE a.{column} = %s AND g.type = 'role'""",
        (res["id"],))
    groups = dict(cur.fetchall())
    missing = [r for r in (OWNERS, EDITORS, VIEWERS) if r not in groups]
    if missing:
        raise Fatal(f"Missing role groups for {res['label']}: {missing}. "
                    "The resource looks corrupted or nonexistent.")
    return groups


# ---------------------------------------------------------------------------
# Guests group repair (mirrors HomeDBManager)
# ---------------------------------------------------------------------------

def _special_user_ids(cur):
    cur.execute("SELECT l.email, u.id FROM users u JOIN logins l ON l.user_id = u.id "
                "WHERE l.email IN (%s, %s)", (EVERYONE_EMAIL, ANONYMOUS_USER_EMAIL))
    found = dict(cur.fetchall())
    return found.get(EVERYONE_EMAIL), found.get(ANONYMOUS_USER_EMAIL)


def _filter_everyone(cur, user_ids):
    """Replicates UsersManager.filterEveryone: removes the 'everyone@' user
    unless 'anon@' is present."""
    everyone_id, anon_id = _special_user_ids(cur)
    if anon_id is not None and anon_id in user_ids:
        return user_ids
    return {u for u in user_ids if u != everyone_id}


def _set_group_users(cur, group_id, target_user_ids):
    """Aligns the group's members with target_user_ids. Returns (added, removed)."""
    cur.execute("SELECT user_id FROM group_users WHERE group_id = %s", (group_id,))
    current = {r[0] for r in cur.fetchall()}
    to_add = target_user_ids - current
    to_remove = current - target_user_ids
    if to_remove:
        cur.execute("DELETE FROM group_users WHERE group_id = %s AND user_id in %s",
                    (group_id, tuple(to_remove)))
    if to_add:
        psycopg2.extras.execute_values(
            cur, "INSERT INTO group_users (group_id, user_id) VALUES %s",
            [(group_id, u) for u in to_add])
    return to_add, to_remove

def _get_effective_role(role):
    if role == MEMBERS or role == GUESTS:
        return VIEWERS
    return role


def repair_workspace_guests(cur, workspace_id):
    """The workspace's guests group = direct users of the workspace's
    non-deleted docs (see _repairWorkspaceGuests)."""
    cur.execute(
        """SELECT g.id FROM acl_rules a JOIN groups g ON g.id = a.group_id
           WHERE a.workspace_id = %s AND g.name = 'guests'""", (workspace_id,))
    row = cur.fetchone()
    if not row:
        raise Fatal(f"Guests group not found for workspace {workspace_id}.")
    guest_group_id = row[0]
    cur.execute(
        """SELECT DISTINCT gu.user_id
           FROM docs d
           JOIN acl_rules a ON a.doc_id = d.id
           JOIN group_users gu ON gu.group_id = a.group_id
           WHERE d.workspace_id = %s AND d.removed_at IS NULL""",
        (workspace_id,))
    users = _filter_everyone(cur, {r[0] for r in cur.fetchall()})
    return _set_group_users(cur, guest_group_id, users)


def repair_org_guests(cur, org_id):
    """The org's guests group = direct users of the org's non-deleted
    workspaces, including the workspaces' guests groups
    (see _repairOrgGuests — must be called AFTER repair_workspace_guests)."""
    cur.execute(
        """SELECT g.id FROM acl_rules a JOIN groups g ON g.id = a.group_id
           WHERE a.org_id = %s AND g.name = 'guests'""", (org_id,))
    row = cur.fetchone()
    if not row:
        raise Fatal(f"Guests group not found for org {org_id}.")
    guest_group_id = row[0]
    cur.execute(
        """SELECT DISTINCT gu.user_id
           FROM workspaces w
           JOIN acl_rules a ON a.workspace_id = w.id
           JOIN group_users gu ON gu.group_id = a.group_id
           WHERE w.org_id = %s AND w.removed_at IS NULL""",
        (org_id,))
    users = _filter_everyone(cur, {r[0] for r in cur.fetchall()})
    return _set_group_users(cur, guest_group_id, users)


def repair_parents(cur, res):
    """Repairs the parents' guests groups after a change, in the same order
    as HomeDBManager (workspace first, then org)."""
    if res["kind"] == "doc":
        repair_workspace_guests(cur, res["workspace_id"])
        repair_org_guests(cur, res["org_id"])
    elif res["kind"] == "workspace":
        repair_org_guests(cur, res["org_id"])
    # Nothing to repair above an org.

def get_roles(cur, res, max_inherited_role: MAX_INHERITED_ROLE = OWNERS):
    groups = get_role_groups(cur, res)
    members = {}
    if max_inherited_role is None:
        return members

    for role in ROLE_GROUP_NAMES:
        if role not in groups:
            continue
        cur.execute(
            """SELECT l.display_email, u.name FROM group_users gu
               JOIN users u ON u.id = gu.user_id
               JOIN logins l ON l.user_id = u.id
               WHERE gu.group_id = %s ORDER BY l.email""",
            (groups[role],))
        members[role] = cur.fetchall()

    # Apply the mex inherited role
    for role in ROLE_GROUP_NAMES:
        if (role == max_inherited_role):
            break
        members[max_inherited_role] += members[role]
        del members[role]

    return members

def get_max_inherited_role(cur, res, max: MAX_INHERITED_ROLE) -> MAX_INHERITED_ROLE:
    groups = get_role_groups(cur, res)
    max_inherited_role = None
    if max is None:
        return None

    for role in ROLE_GROUP_NAMES:
        if role not in groups:
            continue
        cur.execute(
            """SELECT sg.name 
                FROM group_groups gg
                JOIN groups sg ON gg.subgroup_id = sg.id
                WHERE gg.group_id = %s AND sg.type = 'role'
            """,
            (groups[role],))
        row = cur.fetchone()
        if row:
            max_inherited_role = role
            break

    # ROLE_GROUP_NAMES are ordered from the most permissive to the most restrictive role
    # if the found max_inherited_role has more permissions than the passed maximum role,
    # enforce the passed maximum role.
    if max_inherited_role and ROLE_GROUP_NAMES.index(max_inherited_role) < ROLE_GROUP_NAMES.index(max):
        max_inherited_role = max

    return _get_effective_role(max_inherited_role)

def print_recursive_roles(cur, res, max_inherited_role: MAX_INHERITED_ROLE = "owners"):
    # Let’s fetch the roles before printing anything, so we can have the queries logs before
    roles = get_roles(cur, res, max_inherited_role)

    print(f"Access from {res['label']} (max inherited role = {max_inherited_role}):")
    for role, members in roles.items():
        print(f"  {role}:")
        for email, name in members:
            print(f"    - {email} ({name})")

    print('')
    print('--------')
    print('')

    if res['kind'] == 'doc':
        parent = resolve_resource(cur, { "workspace": res['workspace_id'] })
        print_recursive_roles(cur, parent, get_max_inherited_role(cur, res, max_inherited_role))
    if res['kind'] == 'workspace':
        parent = resolve_resource(cur, { "org": res['org_id'] })
        print_recursive_roles(cur, parent, get_max_inherited_role(cur, res, max_inherited_role))


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

def cmd_list(cur, args):
    res = resolve_resource(cur, extract_resource_identifier(args))
    print_recursive_roles(cur, res)


def cmd_set(cur, args):
    res = resolve_resource(cur, extract_resource_identifier(args))
    if args.role == MEMBERS and res["kind"] != "org":
        raise Fatal("The 'members' role only exists for organisations.")
    user_id, display_email = find_user(cur, args.email)
    groups = get_role_groups(cur, res)

    # Remove the user from the resource's other role groups (a single direct
    # role per resource), then add them to the target group.
    other_group_ids = [gid for role, gid in groups.items()
                       if role != args.role and role != GUESTS]
    if other_group_ids:
        cur.execute("DELETE FROM group_users WHERE user_id = %s AND group_id IN %s",
                    (user_id, tuple(other_group_ids)))
        demoted = cur.rowcount
    else:
        demoted = 0
    cur.execute(
        """INSERT INTO group_users (group_id, user_id) VALUES (%s, %s)
           ON CONFLICT DO NOTHING""",
        (groups[args.role], user_id))
    added = cur.rowcount

    repair_parents(cur, res)

    if added:
        verb = "added to role" if not demoted else "moved to role"
        print(f"{display_email} {verb} '{args.role}' on {res['label']}.")
    elif demoted:
        print(f"{display_email} moved to role '{args.role}' on {res['label']}.")
    else:
        print(f"{display_email} already had role '{args.role}' on {res['label']}; nothing to do.")


def cmd_remove(cur, args):
    res = resolve_resource(cur, extract_resource_identifier(args))
    user_id, display_email = find_user(cur, args.email)
    groups = get_role_groups(cur, res)

    # Safety check: never leave a resource without any owner.
    cur.execute(
        """SELECT count(*) FROM group_users
           WHERE group_id = %s AND user_id != %s""",
        (groups[OWNERS], user_id))
    remaining_owners = cur.fetchone()[0]
    cur.execute("SELECT 1 FROM group_users WHERE group_id = %s AND user_id = %s",
                (groups[OWNERS], user_id))
    is_owner = cur.fetchone() is not None
    # FIXME: could be worth to check properly the inheritance to avoid false panick...
    if is_owner and remaining_owners == 0 and not args.force:
        raise Fatal(f"{display_email} is the last owner of {res['label']}. "
                    "Use --force to remove them anyway.\n"
                    "PS: if there is an owner inherited from the parent resource, it may be safe to force the removal. Use the `list` command on the resource to check that."
                    )

    role_group_ids = [gid for role, gid in groups.items() if role != GUESTS]
    if role_group_ids:
        cur.execute("DELETE FROM group_users WHERE user_id = %s AND group_id IN %s",
                    (user_id, tuple(role_group_ids)))
        removed = cur.rowcount

        repair_parents(cur, res)
    else:
        removed = 0

    if removed:
        print(f"Direct access of {display_email} removed from {res['label']}.")
    else:
        print(f"{display_email} had no direct access to {res['label']}; nothing to do.")
    print("Note: the user may keep access inherited from the parent org or "
          "workspace, or through a team (group of type 'team').")


def cmd_repair_guests(cur, args):
    res = resolve_resource(cur, extract_resource_identifier(args))
    if res["kind"] == "org":
        added, removed = repair_org_guests(cur, res["id"])
    elif res["kind"] == "workspace":
        added, removed = repair_workspace_guests(cur, res["id"])
        repair_org_guests(cur, res["org_id"])
    else:
        raise Fatal("repair-guests applies to --org or --workspace.")
    print(f"Guests group of {res['label']} repaired "
          f"(+{len(added)} / -{len(removed)} users).")


# ---------------------------------------------------------------------------

def add_resource_args(sub):
    sub.add_argument("--org", help="Target organisation (numeric id or domain)")
    sub.add_argument("--workspace", help="Target workspace (numeric id)")
    sub.add_argument("--doc", help="Target document (full id or url_id)")


def main():
    parser = argparse.ArgumentParser(
        description="Modifies Grist access rights directly in the PostgreSQL database.",
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dsn", default="",
                        help="PostgreSQL connection string "
                             "(otherwise PG* environment variables)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Simulate: run everything then roll back the transaction")
    parser.add_argument("-v", "--verbose", action="store_true",
                        help="Log every executed SQL query to stderr")
    parser.add_argument("--log-file",
                        help="Log every executed SQL query to this file")
    parser.add_argument("--syntax-highlighting", action="store", const="default", nargs="?",
                        help="Highlight the syntax for SQL queries (requires --verbose)")
    sub = parser.add_subparsers(dest="command", required=True)

    p_list = sub.add_parser("list", help="List the access rights of a resource")
    add_resource_args(p_list)

    p_set = sub.add_parser("set", help="Grant a role to a user "
                                       "(adds them or changes their role)")
    add_resource_args(p_set)
    p_set.add_argument("--email", required=True, help="The user's email")
    p_set.add_argument("--role", required=True, choices=ASSIGNABLE_ROLES,
                       help="Role to grant ('members': orgs only)")

    p_rm = sub.add_parser("remove", help="Remove all direct access of a user")
    add_resource_args(p_rm)
    p_rm.add_argument("--email", required=True, help="The user's email")
    p_rm.add_argument("--force", action="store_true",
                      help="Allow removing the last owner")

    p_repair = sub.add_parser("repair-guests",
                              help="Recompute the guests group of an org/workspace")
    add_resource_args(p_repair)

    args = parser.parse_args()
    setup_logging(args.verbose, args.log_file)

    logger.debug("Connecting to the database (dsn=%s)", args.dsn or "<PG* environment variables>")
    connection_factory = SqlLoggingConnection
    if highlight and args.verbose and args.syntax_highlighting:
        connection_factory = SynHighlighSqlLoggingConnection
        connection_factory.style = args.syntax_highlighting
    conn = psycopg2.connect(args.dsn, connection_factory=connection_factory)
    conn.initialize(logger)
    try:
        with conn.cursor() as cur:
            {"list": cmd_list, "set": cmd_set, "remove": cmd_remove,
             "repair-guests": cmd_repair_guests}[args.command](cur, args)
        if args.dry_run:
            conn.rollback()
            logger.debug("ROLLBACK (dry-run)")
            print("[dry-run] Transaction rolled back, nothing was written.")
        else:
            conn.commit()
            logger.debug("COMMIT")
    except Fatal as e:
        conn.rollback()
        logger.debug("ROLLBACK (error: %s)", e)
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    finally:
        conn.close()


if __name__ == "__main__":
    main()
